project:
  type: book
  output-dir: docs

book:
  title: "Experimentação Florestal no R"
  reader-mode: true

  page-footer:
    left: |
      Este tutorial foi escrito por Edgar de Souza Vismara e Ximena Mendes de Oliveira.
    right: |
      Este material foi elaborado com <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover2.png
  favicon: cover.png
  author: "Edgar S. Vismara e Ximena M. de Oliveira"
  date: last-modified
  
  chapters:
    - index.qmd
    
    - part: "Parte I: Fundamentos Teóricos" 
      chapters:
      - intro.qmd
      - lin_mod.qmd
      
 
    - part: "Parte II: Delineamento Experimental"   
      chapters:
      - delinea.qmd 
      
    - part: "Parte III: Preparação e Análise de Dados"   
      chapters:
      - pre_pro.qmd 
      - analise.qmd
      
    - part: "Parte IV: Aplicações Florestais"   
      chapters:
      - casos.qmd 
  
      
    - part: "Parte V: Visualização e Boas Práticas"   
      chapters:
      - visual.qmd 
      - boas_praticas.qmd
    
    - part: "Apêndice"   
      chapters:
      - appendix.qmd 
      - recursos.qmd 
  

reference-section-title: references
bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    #- estilo_hd.css
    code-link: true
    self-contained-math: true
   

    author-meta: "Edgar S. Vismara e Ximena M. de Oliveira"
    callout-appearance: simple
  pdf:
    documentclass: scrreprt
    cover-image: cover.png
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub: default

editor: visual

